# Generated by Django 5.2.6 on 2025-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='choice',
            field=models.CharField(blank=True, choices=[('Cтатья', 'Статья'), ('Ссылка', 'Ссылка')], default='Статья', max_length=100, null=True, verbose_name='Вид'),
        ),
    ]
