# Generated by Django 5.2.6 on 2025-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful', '0002_article_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='choice',
            field=models.CharField(blank=True, choices=[('Статья', 'Статья'), ('Ссылка', 'Ссылка')], default='Статья', max_length=100, null=True, verbose_name='Вид'),
        ),
    ]
