# Generated by Django 5.2.6 on 2025-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful', '0003_alter_article_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=310, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативныe документы',
                'db_table': 'document',
                'ordering': ['-id'],
            },
        ),
    ]
