# Generated by Django 5.2.6 on 2025-11-17 19:04

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful', '0004_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Статья / Ссылка', 'verbose_name_plural': 'Статьи / Ссылки'},
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
