# Generated by Django 5.2.6 on 2025-12-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful', '0005_alter_article_options_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
    ]
