# Generated by Django 5.2.6 on 2025-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandunit',
            name='information',
            field=models.CharField(default=1, max_length=1000, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandunit',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='commandunit',
            name='fio',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='commandunit',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='commandunit',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
