# Generated by Django 5.2.6 on 2025-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_commandunit_information_alter_commandunit_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandunit',
            name='information',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Информация'),
        ),
    ]
