# Generated by Django 5.2.6 on 2025-10-05 15:02

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_commandunit_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Диплом / сертификат',
                'verbose_name_plural': 'Дипломы / сертификаты от банка',
                'db_table': 'value',
            },
        ),
    ]
