# Generated by Django 5.2.6 on 2025-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_valueunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=410, unique=True, verbose_name='Slug')),
                ('information', models.TextField(blank=True, max_length=3000, verbose_name='Информация')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'job',
                'ordering': ['-id'],
            },
        ),
    ]
